#!/bin/bash

actions=("shutdown\nrestart\nlock\nlogout\nsleep\nhibernate\nrestart dwm")
action=$(echo -e $actions | rofi -dmenu -i -p "Power ")
case "$action" in
    logout)
        killall xinit
        ;;

    restart)
        systemctl reboot
        ;;

    lock)
        slock
        ;;

    shutdown)
        systemctl poweroff
        ;;

    sleep)
        systemctl suspend
        ;;

    hibernate)
        systemctl hibernate
        ;;
	"restart dwm")
		killall dwm
		;;
esac
