#!/bin/bash

actions=("shutdown\nrestart\nsleep\nhibernate")
action=$(echo -e $actions | rofi -dmenu -i -p "Power ")
case "$action" in
    restart)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    sleep)
        systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
esac
