#! /bin/bash

ICON=$(xrdb -query | grep 'bar.icon'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'bar.text'| awk 'NR==1{print $NF}')

if [ -z $ICON ] || [ -z $FOREGROUND ]; then
    ICON="#ffffff"
    FOREGROUND="#ffffff"
fi

cpu=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1}')

printf " ^c%s^ ^c%s^%s%%  " "$ICON" "$FOREGROUND" "$cpu"
