#! /bin/sh
ICON=$(xrdb -query | grep 'color4'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'foreground'| awk 'NR==1{print $NF}')

if [ -z $ICON ] || [ -z $FOREGROUND ]; then
    ICON="#ffffff"
    FOREGROUND="#ffffff"
fi

date="$(date "+%d-%m-%y, %a")"
time="$(date "+%H:%M")"
echo -ne " ^c${ICON}^ ^c${FOREGROUND}^$date ^c${ICON}^ ^c${FOREGROUND}^$time "
