#! /bin/bash

ICON=$(xrdb -query | grep 'bar.icon'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'bar.text'| awk 'NR==1{print $NF}')

if [ -z $ICON ] || [ -z $FOREGROUND ]; then
    ICON="#ffffff"
    FOREGROUND="#ffffff"
fi

date="$(date "+%d-%m-%y, %a")"
time="$(date "+%H:%M")"
printf " ^c${ICON}^ ^c${FOREGROUND}^$date ^c${ICON}^ ^c${FOREGROUND}^$time "
