#! /bin/sh
ICON=$(xrdb -query | grep 'color4'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'foreground'| awk 'NR==1{print $NF}')

if [ -z $ICON ] || [ -z $FOREGROUND ]; then
    ICON="#ffffff"
    FOREGROUND="#ffffff"
fi

disk=$(df -h $DISK | grep /dev/ | awk '{print $5}')
echo -ne " ^c${ICON}^  ^c${FOREGROUND}^${disk} "
