#! /bin/sh
ICON=$(xrdb -query | grep 'bar.icon'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'bar.text'| awk 'NR==1{print $NF}')

if [ -z $ICON ] || [ -z $FOREGROUND ]; then
    ICON="#ffffff"
    FOREGROUND="#ffffff"
fi

disk=$(df -h $DISK | grep /dev/sda | tr -d % | awk '{print $5}')

[[ "$disk" -gt 80 ]] && printf " ^c${ICON}^ ^c${FOREGROUND}^${disk} "
