#!/bin/bash

[ ! "$(playerctl -p spotify status 2>&1)" = "Playing" ] && exit 33;

# Define cursor icons
ICON=$(xrdb -query | grep 'color4'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'foreground'| awk 'NR==1{print $NF}')

songTitle="$(playerctl metadata title)"
songArtist="$(playerctl metadata artist)"
songInfo="$songTitle - $songArtist ";

#Display output
echo -ne "^c${ICON}^ ^c${FOREGROUND}^${songInfo}";
