#!/bin/bash

#Change this if player changes
playerName="spotify"

[ "$(playerctl -p "$playerName" status 2>&1)" = "No players found" ] && exit 33;

# Define cursor icons
ICON=$(xrdb -query | grep 'bar.icon'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'bar.text'| awk 'NR==1{print $NF}')

if [ -z $ICON ] || [ -z $FOREGROUND ]; then
    ICON="#ffffff"
    FOREGROUND="#ffffff"
fi

songStatus=""
[ "$(playerctl -p $playerName status)" = "Paused" ] && songStatus=" ";

songTitle="$(playerctl -p $playerName metadata title)"
songArtist="$(playerctl -p $playerName metadata artist)"
songInfo="$songTitle - $songArtist $songStatus";

#Display output
printf " ^c${ICON}^  ^c${FOREGROUND}^${songInfo} ";
