#! /bin/sh
ICON=$(xrdb -query | grep 'bar.icon'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'bar.text'| awk 'NR==1{print $NF}')

if [ -z $ICON ] || [ -z $FOREGROUND ]; then
    ICON="#ffffff"
    FOREGROUND="#ffffff"
fi


if $(pidof /usr/bin/obs-ffmpeg-mux > /dev/null); then
    echo " ^c${ICON}^雷^c${FOREGROUND}^Rec "
