#! /bin/bash

ICON=$(xrdb -query | grep 'bar.icon'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'bar.text'| awk 'NR==1{print $NF}')

if [ -z $ICON ] || [ -z $FOREGROUND ]; then
    ICON="#ffffff"
    FOREGROUND="#ffffff"
fi

mem=$(free | grep Mem | awk '{printf("%.2f%"), $3/$2 * 100.0}')

echo " ^c${ICON}^﬙ ^c${FOREGROUND}^$mem "
