#!/bin/sh
APP_PID=$(pidof obs)
RECORDING_PID=$(pidof obs-ffmpeg-mux)

if [ -z "$APP_PID" ]; then
	printf ""
	exit
fi

ICON=$(xrdb -query | grep 'color4'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'foreground'| awk 'NR==1{print $NF}')

if [ -z $ICON ] || [ -z $FOREGROUND ]; then
    ICON="#ffffff"
    FOREGROUND="#ffffff"
fi

if [ -z "$RECORDING_PID" ]; then
	printf " ^c${ICON}^雷 ^c${FOREGROUND}^Not Recording  "
else
	printf " ^c${ICON}^壘 ^c${FOREGROUND}^Recording  "
fi
