#! /bin/sh
ICON=$(xrdb -query | grep 'color4'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'foreground'| awk 'NR==1{print $NF}')

time="$(date "+%H:%M")"
echo -ne " ^c${ICON}^  ^c${FOREGROUND}^${time} "
