#!/bin/sh

# First check internet connection to not get stuck
ping -c 1 8.8.8.8 > /dev/null 2>&1
if [ $? != 0 ]; then 
	echo -ne ""
	exit 33
fi

ICON=$(xrdb -query | grep 'color4'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'foreground'| awk 'NR==1{print $NF}')

if [ -z $ICON ] || [ -z $FOREGROUND ]; then
    ICON="#ffffff"
    FOREGROUND="#ffffff"
fi

if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
    updates_arch=0
fi

if ! updates_aur=$(yay -Qum 2> /dev/null | wc -l); then
    updates_aur=0
fi

updates=$(("$updates_arch" + "$updates_aur"))

[[ "$updates" -gt 0 ]] && echo -ne " ^c${ICON}^  ^c${FOREGROUND}^${updates}  "
