#!/bin/bash

ICON=$(xrdb -query | grep 'color4'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'foreground'| awk 'NR==1{print $NF}')

if [ -z $ICON ] || [ -z $FOREGROUND ]; then
    ICON="#ffffff"
    FOREGROUND="#ffffff"
fi

volume=$(pamixer --get-volume)

echo -ne " ^c${ICON}^墳 ^c${FOREGROUND}^$volume  "
