#!/bin/bash

ICON=$(xrdb -query | grep 'bar.icon'| awk 'NR==1{print $NF}')
FOREGROUND=$(xrdb -query | grep 'bar.text'| awk 'NR==1{print $NF}')

if [ -z $ICON ] || [ -z $FOREGROUND ]; then
    ICON="#ffffff"
    FOREGROUND="#ffffff"
fi

volume=$(pamixer --get-volume)

echo " ^c${ICON}^墳 ^c${FOREGROUND}^$volume "
