#!/bin/sh

while IFS= read -r line; do
  echo "$line" | grep -q -E '^[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}:$'
  # if [[  ]]; then
  #
  # fi
done < "$HOME/.var/app/com.usebottles.bottles/data/bottles/library.yml"
