#! /bin/bash

if [[ -z "$1" ]]; then
    echo "No wallpaper given"
    exit 1
fi

# Set new wallpaper
wal -b "#161616" --saturate 0.4 -i "$1"

# Generate new GTK theme
#oomox-cli -o Custom ~/.cache/wal/colors-oomox

# Change dunst them
#sh ~/.scripts/dunst_xr_theme_changer.sh
#killall dunst
#dunst -conf $HOME/.config/dunst/dunstrc_xr_colors &

# Reset dwm colors
xsetroot -name "fsignal:1"

# Reset dwmblocks colors
killall dwmblocks

dwmblocks &
