#!/bin/sh

DIRECTORY="$1"
[ -z "$2" ] && COMMAND="mpv" || COMMAND="$2"

while true; do
	FILES=$(ls "$DIRECTORY" | sort -r)
	CHOISE=$(printf "%s\n../" "$FILES" | dmenu -i -p "Choose: ")

	[ -z "$CHOISE" ] && exit

	if [ "$CHOISE" = "../" ]; then
		DIRECTORY=$(dirname "$DIRECTORY")
		continue
	fi

	if [ -d "$DIRECTORY/$CHOISE" ]; then
		DIRECTORY="$DIRECTORY/$CHOISE"
	else
		$COMMAND "$DIRECTORY/$CHOISE"
		exit
	fi
done
