#! /bin/sh

xrdb $HOME/.Xresources

# Change dunst them
sh ~/.scripts/dunst_xr_theme_changer.sh
killall dunst
dunst -conf $HOME/.config/dunst/dunstrc_xr_colors &

# Reset dwm colors
xsetroot -name "fsignal:1"

# Reset dwmblocks colors
killall dwmblocks
dwmblocks &
