#!/bin/sh
set -e

PROTON_LINK="https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-26/wine-lutris-GE-Proton8-26-x86_64.tar.xz"
RTP_BASE_URL="https://dl.komodo.jp/rpgmakerweb/run-time-packages"
PREFIX_PATH="$HOME/.RPG_prefix"

check_proton()
{
	if [ ! -d "$PREFIX_PATH" ]; then
		run_wine wineboot

		install_winetricks

		install_all_rtp

		mkdir "$PREFIX_PATH/proton"
		wget -O "/tmp/proton" --no-check-certificate "$PROTON_LINK"
		tar -xf "/tmp/proton" --directory "$PREFIX_PATH/proton"
	fi

}

run()
{
	check_proton

	firejail --noprofile --net=none --env=GAMEID="rpg_games" --env=WINEPREFIX="$PREFIX_PATH" --env=LANG="ja_JP.UTF-8" --env=PROTONPATH="$HOME/.steam/steam/compatibilitytools.d/GE-Proton9-13" umu-run "$1"
	#firejail --noprofile --net=none --env=GAMEID="rpg_games" --env=WINEPREFIX="$PREFIX_PATH" --env=PROTONPATH="$HOME/.steam/steam/compatibilitytools.d/GE-Proton9-9" umu-run "$1"
	#firejail --noprofile --net=none --env=WINEPREFIX="$PREFIX_PATH" --env=LANG="ja_JP.UTF-8" --env=PROTONPATH="$HOME/.steam/steam/compatibilitytools.d/GE-Proton8-28" umu-run "$1"
	#firejail --noprofile --net=none --env=WINEPREFIX="$PREFIX_PATH" --env=LANG='ja_JP.UTF-8' "wine" "$1"
}

run_wine()
{
	echo "RUN: $1"
	WINEPREFIX="$PREFIX_PATH" LANG=ja_JP.UTF-8 wine "$1"
}

run_winecfg()
{
	check_proton

	WINEPREFIX="$PREFIX_PATH" winecfg
}

run_winetricks()
{
	check_proton

	WINEPREFIX="$PREFIX_PATH" winetricks
}

install_winetricks()
{
	WINEPREFIX="$PREFIX_PATH" winetricks d3dcompiler_43 corefonts
}

download_and_install_rtp()
{
	wget -O "/tmp/$1" --no-check-certificate "$RTP_BASE_URL/$1"

	case "$1" in
		*.zip) unzip -o "/tmp/$1" -d "/tmp/rtp/" && find "/tmp/rtp/" -type f -name "*.exe" -exec sh -c "WINEPREFIX=$PREFIX_PATH wine {}" \; && rm -rf /tmp/rtp;;
		*.exe) run_wine "/tmp/$1";;
		*) echo "Invalid name";;
	esac
}

install_all_rtp()
{
	download_and_install_rtp "RPGVXAce_RTP.zip"
	download_and_install_rtp "vx_rtp102e.zip"
	download_and_install_rtp "xp_rtp104e.exe"
	download_and_install_rtp "rpg2003_rtp_installer.zip"
	download_and_install_rtp "rpg2000_rtp_installer.exe"
}


case "$1" in
	"winecfg") run_winecfg ;; 
	"winetricks") run_winetricks ;; 
	"install") install_all_rtp ;; 
	"run") run_wine "$1" ;; 
	*) run "$1" ;;
esac
